using Sirenix.OdinInspector;
using UnityEngine;

[CreateAssetMenu(menuName = "Settings/Team Settings")]
public class TeamSettings : ScriptableObject
{
    [Tooltip("Maximum number of players per team")] [SerializeField]
    private int maxPlayerPerTeam = 4;

    [Tooltip("Number of team")] [SerializeField] [MinValue(2)]
    private int numberOfTeam = 2;

    [Tooltip("Allow tackling between players of the same team")] [SerializeField] 
    private bool allowFriendlyFire = true;
    public int MaxPlayerPerTeam => maxPlayerPerTeam;
    public int NumberOfTeam => numberOfTeam;
    public bool AllowFriendlyFire => allowFriendlyFire;
    public string[] TeamPronouns => teamPronouns;
    public string[] TeamAdjectives => teamAdjectives;

    [Tooltip("Possible team pronouns")] [SerializeField]
    private string[] teamPronouns = {
        "cats", 
        "cyborgs",
        "emos",
        "fellas",
        "gangsters",
        "geeks",
        "helpers",
        "hipsters",
        "jocks",
        "lads",
        "nerds",
        "punks",
        "socialites",
        "stars",
        "weirdos ",
        "zombies",
        "gamers",
        "ninjas",
        "pirates",
        "wizards",
        "squad",
        "team",
        "furries",
        "folks",
        "drunks",
        "yo's",
        "poils",
        "potatoes",
        "losers",
        "winners",
        "squids",
        "dogs",
        "rats",
        "birds",
        "snake",
        "gals",
        "ladies",
        "fraternity",
        "sorrority",
        "bros",
        "foes",
        "artists",
        "programmers",
        "designers",
        "musicians",
        "bears",
        "shoes",
        "teachers",
        "students",
        "kings",
        "admins",
        "queens",
        "managers",
        "legends",
        "baldies",
        "gods",
        "nuggets",
        "richs",
        "poors",
        "weebs",
        "simps",
        "friends",
        "ennemies",
        "memesters",
        "vertices",
        "edges",
        "faces",
        "Xforms",
        "textures",
        "matrixes",
        "concepts",
        "deformations",
        "retopologies",
        "rigs",
        "noobs",
        "booleans",
        "floats",
        "integers",
        "webs",
        "strings",
        "binaries",
        "PHPs",
        "404s",
        "captchas",
        "fonts",
        "vectors",
        "pointers",
        "briefs",
        "loops",
        "mechanics",
        "cubes",
        "triangles",
        "spheres",
        "chamfers",
        "NFT-collectors"
    };

    [Tooltip("Possible team adjectives")]
    [SerializeField]
    private string[] teamAdjectives = {
        "ambitious",
        "athletic",
        "awesome",
        "bad",
        "big",
        "cool",
        "dumb",
        "energetic",
        "good",
        "greasy",
        "great",
        "hairy",
        "intelligent",
        "lazy",
        "mysterious",
        "ordinary",
        "precious",
        "pretty",
        "quirky",
        "repulsive",
        "serious",
        "smart",
        "smelly",
        "standard",
        "strong",
        "successful",
        "terrific",
        "typical",
        "ugly",
        "violent",
        "friendly",
        "crazy",
        "hyperactive",
        "drunk",
        "cheesy",
        "polite",
        "evil",
        "hazardous",
        "weird",
        "funny",
        "old",
        "young",
        "laughing",
        "dancing",
        "running",
        "swimming",
        "working",
        "sleeping",
        "thinking",
        "throwing",
        "dashing",
        "falling",
        "winning",
        "losing",
        "sad",
        "crying",
        "classic",
        "classy",
        "yo",
        "ultimate",
        "final",
        "first",
        "A-grade",
        "angry",
        "hungry",
        "infamous",
        "honest",
        "stupid",
        "organized",
        "scared",
        "happy",
        "chaotic",
        "crazy",
        "all-mighty",
        "weak",
        "small",
        "clean",
        "rich",
        "poor",
        "basic",
        "spoiled",
        "rare",
        "famous",
        "romantic",
        "fast",
        "slow",
        "recursive",
        "genious",
        "hot",
        "cold",
        "fancy",
        "lonely",
        "Shipping",
        "unwrapped",
        "animated",
        "TRUE",
        "FALSE",
        "null",
        "coding",
        "creative"
    };
}
