using Sirenix.OdinInspector;
using UnityEngine;

[CreateAssetMenu(menuName = "Settings/Team Settings")]
public class TeamSettings : ScriptableObject
{
    [Tooltip("Maximum number of players per team")] [SerializeField]
    private int maxPlayerPerTeam = 4;

    [Tooltip("Number of team")] [SerializeField] [MinValue(2)]
    private int numberOfTeam = 2;

    [Tooltip("Allow tackling between players of the same team")] [SerializeField] 
    private bool allowFriendlyFire = true;
    public int MaxPlayerPerTeam => maxPlayerPerTeam;
    public int NumberOfTeam => numberOfTeam;
    public bool AllowFriendlyFire => allowFriendlyFire;
    public string[] TeamPronouns => teamPronouns;
    public string[] TeamAdjectives => teamAdjectives;
    
    [Tooltip("Possible team adjectives")]
    [SerializeField]
    private string[] teamAdjectives = {
        "Ambitious",
        "Alpha",
        "Beta",
        "Athletic",
        "Awesome",
        "Bad",
        "Big",
        "Buggy",
        "Cool",
        "Dumb",
        "Energetic",
        "Good",
        "Greasy",
        "Great",
        "Hairy",
        "Intelligent",
        "Lazy",
        "Mysterious",
        "Ordinary",
        "Precious",
        "Pretty",
        "Quirky",
        "Serious",
        "Smart",
        "Smelly",
        "Standard",
        "Strong",
        "Successful",
        "Terrific",
        "Typical",
        "Ugly",
        "Violent",
        "Friendly",
        "Crazy",
        "Hyperactive",
        "Drunk",
        "Cheesy",
        "Polite",
        "Evil",
        "Hazardous",
        "Weird",
        "Funny",
        "Old",
        "Young",
        "Laughing",
        "Dancing",
        "Running",
        "Swimming",
        "Working",
        "Sleeping",
        "Thinking",
        "Throwing",
        "Dashing",
        "Falling",
        "Winning",
        "Losing",
        "Sad",
        "Crying",
        "Classic",
        "Classy",
        "Yo",
        "Ultimate",
        "Final",
        "First",
        "A-grade",
        "Angry",
        "Hungry",
        "Infamous",
        "Honest",
        "Stupid",
        "Organized",
        "Scared",
        "Happy",
        "Chaotic",
        "Crazy",
        "All-mighty",
        "Weak",
        "Small",
        "Clean",
        "Rich",
        "Poor",
        "Basic",
        "Spoiled",
        "Rare",
        "Famous",
        "Romantic",
        "Fast",
        "Slow",
        "Recursive",
        "Genious",
        "Hot",
        "Cold",
        "Fancy",
        "Lonely",
        "Shipping",
        "Unwrapped",
        "Animated",
        "True",
        "False",
        "Coding",
        "Creative"
    };

    [Tooltip("Possible team pronouns")] [SerializeField]
    private string[] teamPronouns = {
        "Cats",
        "Cyborgs",
        "Emos",
        "Fellas",
        "Gangsters",
        "Geeks",
        "Helpers",
        "Hipsters",
        "Jocks",
        "Lads",
        "Nerds",
        "Punks",
        "Socialites",
        "Stars",
        "Weirdos ",
        "Zombies",
        "Gamers",
        "Ninjas",
        "Pirates",
        "Wizards",
        "Squad",
        "Team",
        "Furries",
        "Folks",
        "Drunks",
        "Yo's",
        "Poils",
        "Potatoes",
        "Losers",
        "Winners",
        "Squids",
        "Dogs",
        "Rats",
        "Birds",
        "Snake",
        "Gals",
        "Ladies",
        "Fraternity",
        "Sorrority",
        "Bros",
        "Foes",
        "Artists",
        "Programmers",
        "Designers",
        "Musicians",
        "Bears",
        "Shoes",
        "Teachers",
        "Students",
        "Kings",
        "Admins",
        "Queens",
        "Managers",
        "Legends",
        "Baldies",
        "Gods",
        "Nuggets",
        "Richs",
        "Poors",
        "Simpletons",
        "Protagonists",
        "Friends",
        "Ennemies",
        "Memesters",
        "Vertices",
        "Faces",
        "Textures",
        "Noobs",
        "Booleans",
        "Floats",
        "Integers",
        "Strings",
        "Binaries",
        "PHPs",
        "404s",
        "Captchas",
        "Fonts",
        "Vectors",
        "Briefs",
        "Loops",
        "Mechanics",
        "Cubes",
        "Triangles",
        "Spheres",
        "NFT-collectors"
    };
}
